### ISSUE TITLE
JWT authentication requires username

### ISSUE THREAD

**Issue by frankpeleato** [m50/setup-sfdx-action#2]
The JWT authentication model requires passing a username as a parameter. However, there is no way to specify the username in this action.

```yml
- name: Setup SFDX
  uses: m50/setup-sfdx-action@1.1.1
  with:
    plugins: skuid-sfdx
    client-id: ${{ secrets.CONNECTED_APP_CONSUMER_KEY }}
    jwt-key: ${{ secrets.JWT_PRIVATE_KEY }}
```

Receiving the following error:
![image](https://user-images.githubusercontent.com/61477401/132055076-9d7f88d6-ec4c-43ca-8e29-83ebf0422fa7.png)
